{"name": "Проверка ошибки логина пользователя c невалидным значением поля email", "status": "passed", "steps": [{"name": "Создаем рандомное слово из 6 символов", "status": "passed", "start": 1714325549218, "stop": 1714325549218}, {"name": "Логинимся пользователем", "status": "passed", "parameters": [{"name": "email", "value": "'yskrls'"}, {"name": "password", "value": "'fvwpqq'"}], "start": 1714325549218, "stop": 1714325549540}], "start": 1714325549218, "stop": 1714325549541, "uuid": "de401304-8d5e-4013-a3cc-a13691efab6e", "historyId": "8a6ac06a254335d994e45e685fcab902", "testCaseId": "8a6ac06a254335d994e45e685fcab902", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_invalid_email_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "1424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}