{"name": "Проверка ошибки логина пользователя c невалидными значениями полей email, password", "status": "passed", "steps": [{"name": "Создаем рандомное слово из 6 символов", "status": "passed", "start": 1714325552047, "stop": 1714325552047}, {"name": "Создаем рандомное слово из 6 символов", "status": "passed", "start": 1714325552047, "stop": 1714325552047}, {"name": "Логинимся пользователем", "status": "passed", "parameters": [{"name": "email", "value": "'bxfoas'"}, {"name": "password", "value": "'ztiwlv'"}], "start": 1714325552047, "stop": 1714325552477}], "start": 1714325552047, "stop": 1714325552478, "uuid": "e0824d30-f33f-458e-be4c-4173ad457c58", "historyId": "27215d35b8dd7ee84709190e39d85e77", "testCaseId": "27215d35b8dd7ee84709190e39d85e77", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_invalid_credentials_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "1424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}